openapi: 3.0.1
info:
  title: PagoPA API Payments
  description: Payments
  termsOfService: https://www.pagopa.gov.it/
  version: 0.0.17
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: Payments receipts API
paths:
  /info:
    get:
      tags:
        - Home
      summary: health check
      description: Return OK if application is started
      operationId: healthCheck
      responses:
        '200':
          description: OK
          headers:
            X-Request-Id:
              description: This header identifies the call
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppInfo'
        '400':
          description: Bad Request
          headers:
            X-Request-Id:
              description: This header identifies the call
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '401':
          description: Unauthorized
          headers:
            X-Request-Id:
              description: This header identifies the call
              schema:
                type: string
        '403':
          description: Forbidden
          headers:
            X-Request-Id:
              description: This header identifies the call
              schema:
                type: string
        '429':
          description: Too many requests
          headers:
            X-Request-Id:
              description: This header identifies the call
              schema:
                type: string
        '500':
          description: Service unavailable
          headers:
            X-Request-Id:
              description: This header identifies the call
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
      security:
        - ApiKey: []
        - Authorization: []
    parameters:
      - name: X-Request-Id
        in: header
        description: >-
          This header identifies the call, if not passed it is self-generated.
          This ID is returned in the response.
        schema:
          type: string
  /payments/{organizationfiscalcode}/receipts:
    get:
      tags:
        - Payments receipts API
      summary: Return the list of the organization receipts.
      operationId: getOrganizationReceipts
      parameters:
        - name: organizationfiscalcode
          in: path
          description: Organization fiscal code, the fiscal code of the Organization.
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: Number of elements on one page
          required: false
          schema:
            maximum: 999
            type: integer
            format: int32
        - name: page
          in: query
          description: Page number. Page value starts from 0
          required: false
          schema:
            minimum: 0
            type: integer
            format: int32
            default: 0
        - name: debtor
          in: query
          description: Filter by debtor
          required: false
          schema:
            type: string
        - name: service
          in: query
          description: Filter by service
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Obtained all organization payment positions.
          headers:
            X-Request-Id:
              description: This header identifies the call
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReceiptsInfo'
        '401':
          description: Wrong or missing function key.
          headers:
            X-Request-Id:
              description: This header identifies the call
              schema:
                type: string
        '404':
          description: No receipts found.
          headers:
            X-Request-Id:
              description: This header identifies the call
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '500':
          description: Service unavailable.
          headers:
            X-Request-Id:
              description: This header identifies the call
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
      security:
        - ApiKey: []
        - Authorization: []
    parameters:
      - name: X-Request-Id
        in: header
        description: >-
          This header identifies the call, if not passed it is self-generated.
          This ID is returned in the response.
        schema:
          type: string
  /payments/{organizationfiscalcode}/receipts/{iuv}:
    get:
      tags:
        - Payments receipts API
      summary: Return the details of a specific receipt.
      operationId: getReceiptByIUV
      parameters:
        - name: organizationfiscalcode
          in: path
          description: Organization fiscal code, the fiscal code of the Organization.
          required: true
          schema:
            type: string
        - name: iuv
          in: path
          description: >-
            IUV (Unique Payment Identification). Alphanumeric code that uniquely
            associates and identifies three key elements of a payment: reason,
            payer, amount
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Obtained receipt details.
          headers:
            X-Request-Id:
              description: This header identifies the call
              schema:
                type: string
          content:
            application/xml:
              schema:
                type: string
        '401':
          description: Wrong or missing function key.
          headers:
            X-Request-Id:
              description: This header identifies the call
              schema:
                type: string
        '404':
          description: No receipt found.
          headers:
            X-Request-Id:
              description: This header identifies the call
              schema:
                type: string
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ProblemJson'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '422':
          description: Unable to process the request.
          headers:
            X-Request-Id:
              description: This header identifies the call
              schema:
                type: string
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ProblemJson'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '500':
          description: Service unavailable.
          headers:
            X-Request-Id:
              description: This header identifies the call
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
      security:
        - ApiKey: []
        - Authorization: []
    parameters:
      - name: X-Request-Id
        in: header
        description: >-
          This header identifies the call, if not passed it is self-generated.
          This ID is returned in the response.
        schema:
          type: string
components:
  schemas:
    ProblemJson:
      type: object
      properties:
        title:
          type: string
          description: >-
            A short, summary of the problem type. Written in english and
            readable for engineers (usually not suited for non technical
            stakeholders and not localized); example: Service Unavailable
        status:
          maximum: 600
          minimum: 100
          type: integer
          description: >-
            The HTTP status code generated by the origin server for this
            occurrence of the problem.
          format: int32
          example: 200
        detail:
          type: string
          description: >-
            A human readable explanation specific to this occurrence of the
            problem.
          example: There was an error processing the request
    PageInfo:
      required:
        - items_found
        - more_pages
        - page
      type: object
      properties:
        page:
          type: integer
          description: Page number
          format: int32
        limit:
          type: integer
          description: Number of items per page
          format: int32
        items_found:
          type: integer
          description: Number of items found
          format: int32
        more_pages:
          type: boolean
          description: More elements on the following pages
    ReceiptModelResponse:
      type: object
      properties:
        organizationFiscalCode:
          type: string
        iuv:
          type: string
        debtorFiscalCode:
          type: string
    ReceiptsInfo:
      required:
        - page_info
        - receipts_list
      type: object
      properties:
        receipts_list:
          type: array
          items:
            $ref: '#/components/schemas/ReceiptModelResponse'
        page_info:
          $ref: '#/components/schemas/PageInfo'
    AppInfo:
      type: object
      properties:
        name:
          type: string
        version:
          type: string
        environment:
          type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      description: The API key to access this function app.
      name: Ocp-Apim-Subscription-Key
      in: header
    Authorization:
      type: http
      description: JWT token get after Azure Login
      scheme: bearer
      bearerFormat: JWT
