<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="pspForNode" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:pspfn="http://pagopa-api.pagopa.gov.it/psp/pspForNode.xsd" xmlns:tns="http://pagopa-api.pagopa.gov.it/psp/pspForNode.wsdl" targetNamespace="http://pagopa-api.pagopa.gov.it/psp/pspForNode.wsdl">

    <wsdl:types>
        <xsd:schema version="1.0.0">
            <xsd:import schemaLocation="pspForNode.xsd" namespace="http://pagopa-api.pagopa.gov.it/psp/pspForNode.xsd" />
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="pspNotifyPaymentReq">
        <wsdl:part name="requestBody" element="pspfn:pspNotifyPaymentReq" />
    </wsdl:message>
    <wsdl:message name="pspNotifyPaymentRes">
        <wsdl:part name="responseBody" element="pspfn:pspNotifyPaymentRes" />
    </wsdl:message>

    <wsdl:portType name="pspForNode_PortType">
        <wsdl:operation name="pspNotifyPayment">
            <wsdl:documentation>
Notify the outcome of a payment transaction started on any PagoPA client and executed on a payment gateway integrated with Payment Manager.

if outcome is OK, the PSP will receive a transfer found on a technical account. Therefore the PSP shall : 

- close the payment by using the *sendPaymentOutcome* message using the *paymentToken* on the request.
- trasfer founds to the account according to the *transferList* element.

if outcome is KO, the PSP can use this information to balance payment gateway transaction and PSP transfers
     

            </wsdl:documentation>

            <wsdl:input message="tns:pspNotifyPaymentReq" wsam:Action="http://pagopa-api.pagopa.gov.it/service/psp/pspForNode/pspNotifyPaymentReq" />
            <wsdl:output message="tns:pspNotifyPaymentRes" wsam:Action="http://pagopa-api.pagopa.gov.it/service/psp/pspForNode/pspNotifyPaymentRes" />
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="pspForNode_Binding" type="tns:pspForNode_PortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />

        <wsdl:operation name="pspNotifyPayment">
            <soap:operation soapAction="pspNotifyPayment" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="pspForNode_Service">
        <wsdl:port name="pspForNode_Port" binding="tns:pspForNode_Binding">
            <soap:address location="http://pagopa-api.pagopa.gov.it/service/psp/pspForNode" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>