<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="pspForNode" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:pspfn="http://pagopa-api.pagopa.gov.it/psp/pspForNode.xsd" xmlns:tns="http://pagopa-api.pagopa.gov.it/psp/pspForNode.wsdl" targetNamespace="http://pagopa-api.pagopa.gov.it/psp/pspForNode.wsdl">

    <wsdl:types>
        <xsd:schema version="1.0.0">
            <xsd:import schemaLocation="pspForNode.xsd" namespace="http://pagopa-api.pagopa.gov.it/psp/pspForNode.xsd" />
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="pspSendPaymentReq">
        <wsdl:part name="requestBody" element="pspfn:pspSendPaymentReq" />
    </wsdl:message>
    <wsdl:message name="pspSendPaymentRes">
        <wsdl:part name="responseBody" element="pspfn:pspSendPaymentRes" />
    </wsdl:message>

    <wsdl:portType name="pspForNode_PortType">
        <wsdl:operation name="pspSendPayment">
            <wsdl:input message="tns:pspSendPaymentReq" wsam:Action="http://pagopa-api.pagopa.gov.it/service/psp/pspForNode/pspSendPaymentReq" />
            <wsdl:output message="tns:pspSendPaymentRes" wsam:Action="http://pagopa-api.pagopa.gov.it/service/psp/pspForNode/pspSendPaymentRes" />
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="pspForNode_Binding" type="tns:pspForNode_PortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />

        <wsdl:operation name="pspSendPayment">
            <soap:operation soapAction="pspSendPayment" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="pspForNode_Service">
        <wsdl:port name="pspForNode_Port" binding="tns:pspForNode_Binding">
            <soap:address location="http://pagopa-api.pagopa.gov.it/service/psp/pspForNode" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
